# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# http://go.microsoft.com/fwlink/?LinkId=248929

name: Lint

on:
  pull_request:
    branches: "main"
    paths-ignore:
      - LICENSE
      - '.nuget/*'
      - build/*.in

permissions: {}

jobs:
  analyze:
    permissions:
      contents: read
      packages: read
      statuses: write
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@12562e48d7059cf666c43a4ecb0d3b5a2b31bd9e # v8.4.0
        env:
          DEFAULT_BRANCH: origin/main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CHECKOV: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_CSHARP: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_POWERSHELL: true
          VALIDATE_GITLEAKS: true
          VALIDATE_YAML: true
