# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# http://go.microsoft.com/fwlink/?LinkId=248929

name: 'CMake (Windows 8.1)'

on:
  push:
    branches: "main"
    paths-ignore:
      - '*.md'
      - LICENSE
      - '.azuredevops/**'
      - '.nuget/*'
      - build/*.cmd
      - build/*.json
      - build/*.props
      - build/*.ps1
      - build/*.targets
  pull_request:
    branches: "main"
    paths-ignore:
      - '*.md'
      - LICENSE
      - '.azuredevops/**'
      - '.nuget/*'
      - build/*.cmd
      - build/*.json
      - build/*.props
      - build/*.ps1
      - build/*.targets

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    strategy:
      fail-fast: false

      matrix:
        toolver: ['14.29', '14']
        build_type: [x64-Debug, x64-Release]
        arch: [amd64]
        include:
          - toolver: '14.29'
            build_type: x86-Debug
            arch: amd64_x86
          - toolver: '14.29'
            build_type: x86-Release
            arch: amd64_x86
          - toolver: '14'
            build_type: x86-Debug
            arch: amd64_x86
          - toolver: '14'
            build_type: x86-Release
            arch: amd64_x86
          - toolver: '14'
            build_type: x64-Debug-Clang
            arch: amd64
          - toolver: '14'
            build_type: x64-Release-Clang
            arch: amd64
          - toolver: '14'
            build_type: x86-Debug-Clang
            arch: amd64_x86
          - toolver: '14'
            build_type: x86-Release-Clang
            arch: amd64_x86

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 'Install Ninja'
        run: choco install ninja

      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch: ${{ matrix.arch }}
          toolset: ${{ matrix.toolver }}

      - name: 'Configure CMake'
        working-directory: ${{ github.workspace }}
        run: cmake --preset=${{ matrix.build_type }}

      - name: 'Build'
        working-directory: ${{ github.workspace }}
        run: cmake --build out\build\${{ matrix.build_type }}

      - name: 'Clean up'
        working-directory: ${{ github.workspace }}
        run: Remove-Item -Path out -Recurse -Force

      - name: 'Configure CMake (Spectre)'
        working-directory: ${{ github.workspace }}
        run: cmake --preset=${{ matrix.build_type }} -DENABLE_SPECTRE_MITIGATION=ON

      - name: 'Build (Spectre)'
        working-directory: ${{ github.workspace }}
        run: cmake --build out\build\${{ matrix.build_type }}

      - name: 'Clean up'
        working-directory: ${{ github.workspace }}
        run: Remove-Item -Path out -Recurse -Force

      - name: 'Configure CMake (DLL)'
        working-directory: ${{ github.workspace }}
        run: cmake --preset=${{ matrix.build_type }} -DBUILD_SHARED_LIBS=ON

      - name: 'Build (DLL)'
        working-directory: ${{ github.workspace }}
        run: cmake --build out\build\${{ matrix.build_type }}
