# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# http://go.microsoft.com/fwlink/?LinkId=248929

name: MSBuild

on:
  push:
    branches: "main"
    paths-ignore:
      - '*.md'
      - LICENSE
      - '.azuredevops/**'
      - '.nuget/*'
      - build/*
  pull_request:
    branches: "main"
    paths-ignore:
      - '*.md'
      - LICENSE
      - '.azuredevops/**'
      - '.nuget/*'
      - build/*

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022 # has v142 tools but not v142 spectre libs

    strategy:
      fail-fast: false

      matrix:
        vs: [2019, 2022]
        build_type: [Debug, Release]
        platform: [x86, x64, ARM64]
        exclude:
          - vs: 2019
            platform: ARM64

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

      - if: matrix.platform != 'ARM64'
        name: Build (Windows 8.1)
        working-directory: ${{ github.workspace }}
        run: >
          msbuild /m /p:Configuration=${{ matrix.build_type }} /p:Platform=${{ matrix.platform }}
          DirectXTK_Desktop_${{ matrix.vs }}.sln

      - name: 'Build (Windows 10)'
        working-directory: ${{ github.workspace }}
        run: >
          msbuild /m /p:Configuration=${{ matrix.build_type }} /p:Platform=${{ matrix.platform }}
          DirectXTK_Desktop_${{ matrix.vs }}_Win10.sln

      - if: matrix.vs == '2022'
        name: 'Build (UWP)'
        working-directory: ${{ github.workspace }}
        run: >
          msbuild /m /p:Configuration=${{ matrix.build_type }} /p:Platform=${{ matrix.platform }}
          DirectXTK_Windows10_2022.sln

      - if: matrix.platform != 'ARM64' && matrix.vs != '2019'
        name: 'Build (Windows 8.1 w/ Spectre)'
        working-directory: ${{ github.workspace }}
        run: >
          msbuild /m /p:Configuration=${{ matrix.build_type }} /p:Platform=${{ matrix.platform }}
          /p:SpectreMitigation=Spectre
          DirectXTK_Desktop_${{ matrix.vs }}.sln

      - if: matrix.platform != 'ARM64' && matrix.vs != '2019'
        name: 'Build (Spectre Windows 10)'
        working-directory: ${{ github.workspace }}
        run: >
          msbuild /m /p:Configuration=${{ matrix.build_type }} /p:Platform=${{ matrix.platform }}
          /p:SpectreMitigation=Spectre
          DirectXTK_Desktop_${{ matrix.vs }}_Win10.sln
